# Generated by Django 5.2 on 2025-04-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_som', models.FloatField(default=88, verbose_name='Курс $ → сом')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
        migrations.AlterModelOptions(
            name='cargogroup',
            options={'verbose_name': 'Поставка', 'verbose_name_plural': 'Поставки'},
        ),
        migrations.AlterModelOptions(
            name='cashtransaction',
            options={'verbose_name': 'Денежная операция', 'verbose_name_plural': 'Денежные операции'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='debt',
            options={'verbose_name': 'Долг', 'verbose_name_plural': 'Долги'},
        ),
        migrations.AlterModelOptions(
            name='financeoverview',
            options={'verbose_name': 'Финансовый отчет', 'verbose_name_plural': 'Финансовые отчеты'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
