# Generated by Django 5.2 on 2025-04-07 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_currency_alter_cargogroup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название кассы')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('warehouse', 'Склад'), ('tmp', 'ТМП'), ('hoz', 'Хоз товары'), ('tmp_kassa_1', 'Касса ТМП 1'), ('tmp_kassa_2', 'Касса ТМП 2'), ('hoz_kassa_1', 'Касса Хоз 1'), ('hoz_kassa_2', 'Касса Хоз 2')], max_length=20, unique=True, verbose_name='Этап')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='cashbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cashbox'),
        ),
        migrations.AddField(
            model_name='cashbox',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashboxes', to='core.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='current_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stage', verbose_name='Текущее местоположение'),
        ),
    ]
