# Generated by Django 5.2 on 2025-04-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cashbox_options_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stage',
        ),
        migrations.AddField(
            model_name='product',
            name='sale_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата продажи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('sklad', 'На складе'), ('way', 'В пути'), ('kassa', 'На кассе'), ('sold', 'Продано')], db_index=True, default='sklad', max_length=10),
        ),
    ]
