# Generated by Django 5.2 on 2025-04-10 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_stage_product_sale_date_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
