# Generated by Django 5.2 on 2025-04-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_debt_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='usd_to_som',
            field=models.FloatField(default=1, editable=False, verbose_name='Курс $ → сом (не используется)'),
        ),
    ]
