# Generated by Django 5.2 on 2025-04-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_currency_usd_to_som'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='no_phone',
            field=models.BooleanField(default=False, verbose_name='Нет телефона'),
        ),
    ]
