# Generated by Django 5.2 on 2025-04-18 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_client_no_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма $'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='type',
            field=models.CharField(choices=[('income', 'Поступление'), ('expense', 'Расход'), ('withdrawal', 'Изъятие средств')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_kg',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Вес (кг)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_units',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество (шт)'),
        ),
    ]
