# Generated by Django 5.2 on 2025-04-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cashtransaction_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма ($)'),
        ),
    ]
