# Generated by Django 5.2 on 2025-04-19 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_debt_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='cashbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cashbox'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.client'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.product'),
        ),
    ]
