# Generated by Django 5.2 on 2025-04-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cashtransaction_cashbox_cashtransaction_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='plomb_number',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='Пломба'),
        ),
    ]
