# Generated by Django 5.2 on 2025-04-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_product_plomb_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='plomb_number',
            field=models.FloatField(blank=True, null=True, verbose_name='Пломба'),
        ),
    ]
