# Generated by Django 5.2 on 2025-05-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_product_plomb_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='plomb_number',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Пломба'),
        ),
        migrations.AlterField(
            model_name='product',
            name='transport_cost',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Йул кира ($)'),
        ),
    ]
