# Generated by Django 5.2 on 2025-05-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_product_plomb_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_places',
            field=models.CharField(blank=True, default=0, max_length=100, null=True, verbose_name='Количество мест'),
        ),
    ]
